**Exercise 5 — Feature Engineering Part 1**



```
1. One-Hot Encoding
Pada tahap ini, data teks hasil preprocessing diubah menjadi bentuk numerik menggunakan One-Hot Encoding. Metode yang digunakan adalah `CountVectorizer` dengan `binary=True`, sehingga setiap kata direpresentasikan dengan nilai 1 jika muncul pada teks dan 0 jika tidak muncul.
```

In [ ]:
import pandas as pd

df = pd.read_csv("hasil_preprocessing_exercise_4.csv")

df

           meals_cleaned ingredients_cleaned
0     biss jaggery modak             chicken
1          honey cookies              salmon
2    gingerbread waffles                beef
3  sauerkraut fish salad                pork
4   carrot bean fritters                 NaN
5              apple pie                 NaN
6      quark rhubarb pie                 NaN
7           papaya salad                 NaN

In [ ]:
# Combine the non-null elements of both 'meals_cleaned' and 'ingredients_cleaned' columns
meals = df["meals_cleaned"].dropna().tolist()
ingredients = df["ingredients_cleaned"].dropna().tolist()

documents = meals + ingredients
documents

['biss jaggery modak',
 'honey cookies',
 'gingerbread waffles',
 'sauerkraut fish salad',
 'carrot bean fritters',
 'apple pie',
 'quark rhubarb pie',
 'papaya salad',
 'chicken',
 'salmon',
 'beef',
 'pork']

In [ ]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer

# Mengubah teks menjadi numerik dengan One-Hot Encoding
vectorizer = CountVectorizer(binary=True)

X = vectorizer.fit_transform(documents)

df_onehot = pd.DataFrame(
    X.toarray(),
    columns=vectorizer.get_feature_names_out()
)

df_onehot

,apple,bean,beef,biss,carrot,chicken,cookies,fish,fritters,gingerbread,...,modak,papaya,pie,pork,quark,rhubarb,salad,salmon,sauerkraut,waffles
0,0,0,0,1,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,1
3,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,1,0,1,0
4,0,1,0,0,1,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
5,1,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
6,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,1,1,0,0,0,0
7,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,1,0,0,0
8,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
10,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0



```
2. TF-IDF
Pada tahap ini, data teks diubah menjadi matriks TF-IDF menggunakan `TfidfVectorizer`. TF-IDF memberikan bobot pada kata berdasarkan kemunculannya dalam suatu dokumen dan seberapa umum kata tersebut pada seluruh dokumen.
```

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

# Mengubah teks menjadi matriks TF-IDF
vectorizer = TfidfVectorizer()

X = vectorizer.fit_transform(documents)

df_tfidf = pd.DataFrame(
    X.toarray(),
    columns=vectorizer.get_feature_names_out()
)

df_tfidf

,apple,bean,beef,biss,carrot,chicken,cookies,fish,fritters,gingerbread,...,modak,papaya,pie,pork,quark,rhubarb,salad,salmon,sauerkraut,waffles
0,0.000000,0.00000,0.0,0.57735,0.00000,0.0,0.000000,0.000000,0.00000,0.000000,...,0.57735,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
1,0.000000,0.00000,0.0,0.00000,0.00000,0.0,0.707107,0.000000,0.00000,0.000000,...,0.00000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
2,0.000000,0.00000,0.0,0.00000,0.00000,0.0,0.000000,0.000000,0.00000,0.707107,...,0.00000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.707107
3,0.000000,0.00000,0.0,0.00000,0.00000,0.0,0.000000,0.604392,0.00000,0.000000,...,0.00000,0.000000,0.000000,0.0,0.000000,0.000000,0.519058,0.0,0.604392,0.000000
4,0.000000,0.57735,0.0,0.00000,0.57735,0.0,0.000000,0.000000,0.57735,0.000000,...,0.00000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
5,0.758631,0.00000,0.0,0.00000,0.00000,0.0,0.000000,0.000000,0.00000,0.000000,...,0.00000,0.000000,0.651521,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
6,0.000000,0.00000,0.0,0.00000,0.00000,0.0,0.000000,0.000000,0.00000,0.000000,...,0.00000,0.000000,0.519058,0.0,0.604392,0.604392,0.000000,0.0,0.000000,0.000000
7,0.000000,0.00000,0.0,0.00000,0.00000,0.0,0.000000,0.000000,0.00000,0.000000,...,0.00000,0.758631,0.000000,0.0,0.000000,0.000000,0.651521,0.0,0.000000,0.000000
8,0.000000,0.00000,0.0,0.00000,0.00000,1.0,0.000000,0.000000,0.00000,0.000000,...,0.00000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
9,0.000000,0.00000,0.0,0.00000,0.00000,0.0,0.000000,0.000000,0.00000,0.000000,...,0.00000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,1.0,0.000000,0.000000
10,0.000000,0.00000,1.0,0.00000,0.00000,0.0,0.000000,0.000000,0.00000,0.000000,...,0.00000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
11,0.000000,0.00000,0.0,0.00000,0.00000,0.0,0.000000,0.000000,0.00000,0.000000,...,0.00000,0.000000,0.000000,1.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000



```
3. Applied to the Preprocessed Data
Pada tahap ini, One-Hot Encoding dan TF-IDF diterapkan pada data teks yang telah melalui preprocessing pada Exercise 4. Data yang digunakan berasal dari hasil preprocessing nama makanan pada **Latest Meals** dan bahan pada **Popular Ingredients** dari TheMealDB.
```

In [ ]:
df_preprocessed = pd.DataFrame({
    "prepro": documents
})

df_preprocessed

                   prepro
0      biss jaggery modak
1           honey cookies
2     gingerbread waffles
3   sauerkraut fish salad
4    carrot bean fritters
5               apple pie
6       quark rhubarb pie
7            papaya salad
8                 chicken
9                  salmon
10                   beef
11                   pork

In [ ]:
vectorizer = TfidfVectorizer()

X = vectorizer.fit_transform(df_preprocessed["prepro"])

df_FE = pd.DataFrame(
    X.toarray(),
    columns=vectorizer.get_feature_names_out()
)

df_FE

,apple,bean,beef,biss,carrot,chicken,cookies,fish,fritters,gingerbread,...,modak,papaya,pie,pork,quark,rhubarb,salad,salmon,sauerkraut,waffles
0,0.000000,0.00000,0.0,0.57735,0.00000,0.0,0.000000,0.000000,0.00000,0.000000,...,0.57735,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
1,0.000000,0.00000,0.0,0.00000,0.00000,0.0,0.707107,0.000000,0.00000,0.000000,...,0.00000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
2,0.000000,0.00000,0.0,0.00000,0.00000,0.0,0.000000,0.000000,0.00000,0.707107,...,0.00000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.707107
3,0.000000,0.00000,0.0,0.00000,0.00000,0.0,0.000000,0.604392,0.00000,0.000000,...,0.00000,0.000000,0.000000,0.0,0.000000,0.000000,0.519058,0.0,0.604392,0.000000
4,0.000000,0.57735,0.0,0.00000,0.57735,0.0,0.000000,0.000000,0.57735,0.000000,...,0.00000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
5,0.758631,0.00000,0.0,0.00000,0.00000,0.0,0.000000,0.000000,0.00000,0.000000,...,0.00000,0.000000,0.651521,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
6,0.000000,0.00000,0.0,0.00000,0.00000,0.0,0.000000,0.000000,0.00000,0.000000,...,0.00000,0.000000,0.519058,0.0,0.604392,0.604392,0.000000,0.0,0.000000,0.000000
7,0.000000,0.00000,0.0,0.00000,0.00000,0.0,0.000000,0.000000,0.00000,0.000000,...,0.00000,0.758631,0.000000,0.0,0.000000,0.000000,0.651521,0.0,0.000000,0.000000
8,0.000000,0.00000,0.0,0.00000,0.00000,1.0,0.000000,0.000000,0.00000,0.000000,...,0.00000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
9,0.000000,0.00000,0.0,0.00000,0.00000,0.0,0.000000,0.000000,0.00000,0.000000,...,0.00000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,1.0,0.000000,0.000000
10,0.000000,0.00000,1.0,0.00000,0.00000,0.0,0.000000,0.000000,0.00000,0.000000,...,0.00000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
11,0.000000,0.00000,0.0,0.00000,0.00000,0.0,0.000000,0.000000,0.00000,0.000000,...,0.00000,0.000000,0.000000,1.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000



>Analisis Hasil

Berdasarkan hasil One-Hot Encoding, data teks berhasil diubah menjadi bentuk numerik berupa nilai 0 dan 1. Nilai 1 menunjukkan bahwa suatu kata terdapat pada dokumen, sedangkan nilai 0 menunjukkan bahwa kata tersebut tidak terdapat pada dokumen.

Pada hasil TF-IDF, setiap kata memiliki bobot yang berbeda. Bobot tersebut menunjukkan tingkat kepentingan suatu kata dalam dokumen dibandingkan dengan keseluruhan dokumen. Dengan demikian, hasil feature engineering dapat digunakan sebagai representasi numerik dari data teks hasil preprocessing.

**Exercise 5 - Feature Engineering Part 2**

Bagian ini mengerjakan Part 2 menggunakan data hasil preprocessing dari Exercise 4.

In [ ]:
import pandas as pd

df = pd.read_csv("hasil_preprocessing_exercise_4.csv")

df.head()

           meals_cleaned ingredients_cleaned
0     biss jaggery modak             chicken
1          honey cookies              salmon
2    gingerbread waffles                beef
3  sauerkraut fish salad                pork
4   carrot bean fritters                 NaN

In [ ]:
meals = df['meals_cleaned'].fillna('').astype(str).tolist()
ingrediens = df['ingredients_cleaned'].fillna('').astype(str).tolist()
documents = [m + '' + ing for m, ing in zip(meals, ingrediens)]
documents = [doc.strip() for doc in documents if doc.strip()]

print('Jumlah dokumen:', len(documents))
print('Contoh dokumen:', documents[0] if documents else 'Data Kosong')

Jumlah dokumen: 8
Contoh dokumen: biss jaggery modakchicken

Bagian ini menerapkan tokenisasi, Word2Vec, dan FastText pada data hasil preprocessing yang sama.

## Tokenize Sentence

In [ ]:
import nltk
nltk.download('punkt')
nltk.download('punkt_tab')

from nltk import word_tokenize
from tqdm.auto import tqdm

sentences = [word_tokenize(str(doc).lower()) for doc in tqdm(documents)]
sentences[:5]

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

  0%|          | 0/8 [00:00<?, ?it/s]

[['biss', 'jaggery', 'modakchicken'],
 ['honey', 'cookiessalmon'],
 ['gingerbread', 'wafflesbeef'],
 ['sauerkraut', 'fish', 'saladpork'],
 ['carrot', 'bean', 'fritters']]

# Build Word2Vec Model

In [ ]:
!pip -q install gensim

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.8/27.8 MB 72.6 MB/s eta 0:00:00

In [ ]:
from gensim.models import Word2Vec
import numpy as np
import pandas as pd

model_w2v = Word2Vec(sentences, min_count=1, vector_size=100, window=5, sg=0)

w2v = model_w2v.wv

print("10 kata pertama:", w2v.index_to_key[:10])
print("Ukuran matriks vektor kata:", w2v.vectors.shape)
print("Dimensi setiap vektor:", w2v.vector_size)

10 kata pertama: ['pie', 'salad', 'papaya', 'rhubarb', 'quark', 'apple', 'fritters', 'bean', 'carrot', 'saladpork']
Ukuran matriks vektor kata: (19, 100)
Dimensi setiap vektor: 100

In [ ]:
if w2v.index_to_key:
  kata_contoh = w2v.index_to_key[0]
  print("Kata contoh:", kata_contoh)
  print("Kata yang mirip:", w2v.similar_by_key(kata_contoh, topn=5))

Kata contoh: pie
Kata yang mirip: [('modakchicken', 0.21883945167064667), ('saladpork', 0.21617142856121063), ('wafflesbeef', 0.0931011214852333), ('bean', 0.09291722625494003), ('sauerkraut', 0.07963486760854721)]

In [ ]:
def get_documents_vector(tokens, keyed_vectors):
  valid_vectors = [keyed_vectors[word] for word in tokens if word in keyed_vectors]
  if not valid_vectors:
    return np.zeros(keyed_vectors.vector_size)
  return np.mean(valid_vectors, axis=0)

  X_word2vec = np.array([get_documents_vector(tokens, w2v) for tokens in tqdm(sentences)])
  df_word2vec = pd.DataFrame(X_word2vec)

  display(df_word2vec.head())
  print("Ukuran matriks vektor dokumen Word2Vec:", X_word2vec.shape)

# Visualisasi Word2Vec

In [ ]:
!pip -q install umap-learn plotly

In [ ]:
from umap import UMAP
import plotly.express as px

if len(w2v.index_to_key) >= 3:
  n_neighbors = min(15, len(w2v.index_to_key) - 1)
  coords = UMAP(n_components=2, random_state=42, n_neighbors=n_neighbors).fit_transform(w2v.vectors)

  df_umap_w2v = pd.DataFrame(coords, columns=["umap1", "umap2"])
  df_umap_w2v["word"] = w2v.index_to_key

  fig = px.scatter(df_umap_w2v, x="umap1", y="umap2", text="word", title="Word2Vec Visualization")
  fig.update_traces(textposition = "top center")
  fig.update_layout(height=700)
  fig.show()
else:
  print("Jumlah kata terlalu sedikit untuk visualisasi UMAP.")

/usr/local/lib/python3.13/dist-packages/umap/umap_.py:1952: UserWarning:

n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.

# Build FastText Model

In [ ]:
from gensim.models import FastText

model_fasttext = FastText(sentences, min_count=1, vector_size=100, window=5, min_n=3, max_n=6, sg=1, epochs=10)

fasttext = model_fasttext.wv

print("10 kata pertama:", fasttext.index_to_key[:10])
print("Ukuran matriks vektor kata:", fasttext.vectors.shape)
print("Dimensi setiap vektor:", fasttext.vector_size)

10 kata pertama: ['pie', 'salad', 'papaya', 'rhubarb', 'quark', 'apple', 'fritters', 'bean', 'carrot', 'saladpork']
Ukuran matriks vektor kata: (19, 100)
Dimensi setiap vektor: 100

In [ ]:
if fasttext.index_to_key:
  kata_contoh_fasttext = fasttext.index_to_key[0]
  print("Kata contoh:", kata_contoh_fasttext)
  print("Kata yang mirip:", fasttext.similar_by_key(kata_contoh_fasttext, topn=5))

Kata contoh: pie
Kata yang mirip: [('papaya', 0.16124632954597473), ('fritters', 0.13008467853069305), ('jaggery', 0.12175992876291275), ('bean', 0.10771721601486206), ('modakchicken', 0.0902363508939743)]

In [ ]:
X_fasttext = np.array([get_documents_vector(doc, fasttext) for doc in sentences])
df_fasttext = pd.DataFrame(X_fasttext)

display(df_fasttext.head())
print("Ukuran matriks vektor dokumen FastText:", X_fasttext.shape)

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
0,0.000358,-0.000611,-0.000426,-0.000375,-0.000262,0.000455,0.000562,-0.000049,0.000596,-0.000155,...,-0.000154,0.000808,0.001805,0.000357,0.000514,0.000236,-0.000638,-0.000274,-0.001692,-0.001295
1,-0.001148,0.000435,-0.000348,0.000081,0.000033,0.001639,-0.000740,0.000308,-0.000131,0.000490,...,-0.000581,-0.000441,0.000426,0.000412,-0.000825,0.000111,0.000074,-0.000486,0.000914,0.000830
2,0.000544,0.000383,-0.000339,-0.000889,-0.000523,0.001130,-0.000223,0.000171,0.000522,-0.000551,...,0.000458,-0.000535,0.000129,-0.000836,0.000188,-0.000337,-0.001494,0.001175,-0.001415,-0.000986
3,-0.000246,0.000236,0.001186,-0.001131,-0.001067,-0.000032,-0.000881,-0.000461,0.000830,-0.000241,...,-0.000033,0.000268,-0.000039,0.000930,0.000042,-0.000379,-0.000697,0.000777,0.000245,-0.000904
4,-0.000057,-0.000085,0.000977,0.000592,0.000776,0.001046,0.000186,-0.000896,0.000625,-0.000031,...,-0.000388,0.000603,0.000987,-0.000589,-0.000628,-0.000797,0.000498,-0.000543,-0.000099,0.000371

Ukuran matriks vektor dokumen FastText: (8, 100)

# Visualisasi FastText

In [ ]:
if len(fasttext.index_to_key) >= 3:
  n_neighbors = min(15, len(fasttext.index_to_key) - 1)
  coords_fasttext = UMAP(n_components=2, random_state=42, n_neighbors=n_neighbors).fit_transform(fasttext.vectors)

  df_umap_fasttext = pd.DataFrame(coords_fasttext, columns=["umap1", "umap2"])
  df_umap_fasttext["word"] = fasttext.index_to_key

  fig = px.scatter(df_umap_fasttext, x="umap1", y="umap2", text="word", title="FastText Visualization")
  fig.update_traces(textposition = "top center")
  fig.update_layout(height=700)
  fig.show()
else:
  print("Jumlah kata terlalu sedikit untuk visualisasi UMAP.")

/usr/local/lib/python3.13/dist-packages/umap/umap_.py:1952: UserWarning:

n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.

# Analisis Hasil Part 2

Word2Vec dan FastText menghasilkan representasi teks dalam bentuk vektor berdimensi 100. Pada Word2Vec, vektor kata dipelajari berdasarkan konteks kata disekitarnya. FastText juga memanfaatkan potongan katakter(character n-grams) sehingga mempertimbangkan struktur subkata. Vektor dokumen diperoleh dengan menghitung rata-rata vektor kata yang terdapat di dalam setiap dokumen.

Pada visualisasi UMAP, kata-kata yang letaknya berdekatan memiliki representasi vektor yang relatif berdekatan menurut model. Namun, kedekatan tersebut tidak selalu berarti kata-kata itu benar-benar sinonim. Karena data yang digunakan berupa nama makanan dan bahan, hasil kemiripan kata perlu ditafsirkan berdasarkan konteks data tersebut. Kualitas hasil juga dipengaruhi oleh jumlah dan variasi teks yang tersedia